### ISSUE TITLE
Server Error with 1.16

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/PM-Beacons#17] opened 2020-06-29 06:51 UTC
[08:46:36] [Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function pocketmine\network\mcpe\protocol\types\NetworkInventoryAction::read(), 1 passed in phar:///home/minecraft/plugins/pm-beacons.phar/src/jasonwynn10/beacon/packet/InventoryTransactionPacketV2.php on line 15 and exactly 2 expected" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/types/NetworkInventoryAction" at line 90

PM Beacons Latest PR Build
Reproduce: 1 Step, Install PM Beacons
                     2 Step, Click on a Block

**Comment by jasonw4331** [comment] 2020-06-29 13:12
duplicate of #16

**Closed as completed by jasonw4331** 2020-06-29 13:12 UTC
